// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_3eJ2QlLHAU5WvJoIXBFsKKvfJEHw78',
    appId: '1:355886157679:web:e0fe7f5d9dcc64317ba29a',
    messagingSenderId: '355886157679',
    projectId: 'mun-thrift',
    authDomain: 'mun-thrift.firebaseapp.com',
    storageBucket: 'mun-thrift.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAibzRrtey4kAcT4x1z0aKVDAkSfTuQqU4',
    appId: '1:355886157679:android:6297c5474938d5397ba29a',
    messagingSenderId: '355886157679',
    projectId: 'mun-thrift',
    storageBucket: 'mun-thrift.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUwwZT7ftNP-cUhNPHcdl-tJbzsG8eVmo',
    appId: '1:355886157679:ios:8337f87fce60c5297ba29a',
    messagingSenderId: '355886157679',
    projectId: 'mun-thrift',
    storageBucket: 'mun-thrift.firebasestorage.app',
    iosBundleId: 'com.example.comp4768MunThrift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUwwZT7ftNP-cUhNPHcdl-tJbzsG8eVmo',
    appId: '1:355886157679:ios:8337f87fce60c5297ba29a',
    messagingSenderId: '355886157679',
    projectId: 'mun-thrift',
    storageBucket: 'mun-thrift.firebasestorage.app',
    iosBundleId: 'com.example.comp4768MunThrift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2_3eJ2QlLHAU5WvJoIXBFsKKvfJEHw78',
    appId: '1:355886157679:web:61f086f3d15de6997ba29a',
    messagingSenderId: '355886157679',
    projectId: 'mun-thrift',
    authDomain: 'mun-thrift.firebaseapp.com',
    storageBucket: 'mun-thrift.firebasestorage.app',
  );

}