import 'dart:typed_data';
import 'package:comp4768_mun_thrift/models/item.dart';
import 'package:comp4768_mun_thrift/models/trade_offer.dart';
import 'package:comp4768_mun_thrift/services/auth_service.dart';
import 'package:comp4768_mun_thrift/services/firestore_service.dart';
import 'package:comp4768_mun_thrift/services/storage_service.dart';
import 'package:comp4768_mun_thrift/controllers/user_info_controller.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';

class TradeOfferScreen extends ConsumerStatefulWidget {
  final String requestedItemId;
  final String requestedItemTitle;
  final String sellerId;

  const TradeOfferScreen({
    super.key,
    required this.requestedItemId,
    required this.requestedItemTitle,
    required this.sellerId,
  });

  @override
  ConsumerState<TradeOfferScreen> createState() => _TradeOfferScreenState();
}

class _TradeOfferScreenState extends ConsumerState<TradeOfferScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _meetupLocationController = TextEditingController();

  ItemCondition _selectedCondition = ItemCondition.good;
  final List<XFile> _selectedImages = [];
  bool _isSubmitting = false;

  final ImagePicker _picker = ImagePicker();

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _meetupLocationController.dispose();
    super.dispose();
  }

  Future<void> _pickImages() async {
    try {
      // For web, use pickMultiImage, for mobile also works
      final List<XFile> images = await _picker.pickMultiImage(imageQuality: 85);
      if (images.isNotEmpty) {
        setState(() {
          // Calculate how many more images we can add
          final remainingSlots = 5 - _selectedImages.length;
          final imagesToAdd = images.take(remainingSlots).toList();
          _selectedImages.addAll(imagesToAdd);
        });

        if (images.length > 5 - (_selectedImages.length - images.length)) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Maximum 5 images allowed'),
                backgroundColor: Colors.orange,
              ),
            );
          }
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error picking images: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _submitTradeOffer() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (_selectedImages.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please add at least one image of your item'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    setState(() {
      _isSubmitting = true;
    });

    try {
      final user = ref.read(authStateChangesProvider).value;
      if (user == null) {
        throw Exception('User not logged in');
      }

      // Get user info
      final userInfoAsync = ref.read(userInfoControllerProvider(user.uid));
      final userInfo = userInfoAsync.value;
      if (userInfo == null) {
        throw Exception('User info not found');
      }

      // Upload images
      final storageService = ref.read(storageServiceProvider);
      final List<String> imageUrls = [];

      for (int i = 0; i < _selectedImages.length; i++) {
        final imageBytes = await _selectedImages[i].readAsBytes();
        final path = storageService.generateItemImagePath(
          user.uid,
          'trade_${DateTime.now().millisecondsSinceEpoch}',
          i,
        );
        final imageUrl = await storageService.uploadImageBytes(
          imageBytes,
          path,
        );
        imageUrls.add(imageUrl);
      }

      // Create trade offer
      final tradeOffer = TradeOffer(
        id: '', // Will be generated by Firestore
        requestedItemId: widget.requestedItemId,
        requestedItemTitle: widget.requestedItemTitle,
        sellerId: widget.sellerId,
        buyerId: user.uid,
        buyerName: userInfo.name,
        buyerEmail: user.email ?? '',
        offeredItemTitle: _titleController.text.trim(),
        offeredItemDescription: _descriptionController.text.trim(),
        offeredItemCondition: _selectedCondition,
        offeredItemImageUrls: imageUrls,
        meetupLocation: _meetupLocationController.text.trim(),
        status: TradeOfferStatus.pending,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // Save to Firestore
      final firestoreService = ref.read(firestoreServiceProvider);
      final tradeOfferId = await firestoreService.createTradeOffer(tradeOffer);

      // Create notification for seller
      await firestoreService.createNotification(
        userId: widget.sellerId,
        type: 'tradeRequest',
        title: 'New Trade Offer',
        message:
            '${userInfo.name} wants to trade for "${widget.requestedItemTitle}"',
        tradeOfferId: tradeOfferId,
        fromUserId: user.uid,
        fromUserName: userInfo.name,
      );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Trade offer submitted successfully!'),
            backgroundColor: Colors.green,
          ),
        );
        context.pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to submit trade offer: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSubmitting = false;
        });
      }
    }
  }

  void _removeImage(int index) {
    setState(() {
      _selectedImages.removeAt(index);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Make Trade Offer')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Info card
              Card(
                color: Colors.blue[50],
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Trading for:',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        widget.requestedItemTitle,
                        style: const TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 24),

              // Item title
              const Text(
                'What are you offering?',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(
                  labelText: 'Item Title',
                  hintText: 'e.g., Nintendo Switch Console',
                  border: OutlineInputBorder(),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter an item title';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Description
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(
                  labelText: 'Description',
                  hintText: 'Describe your item in detail',
                  border: OutlineInputBorder(),
                ),
                maxLines: 4,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter a description';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Condition
              const Text(
                'Condition',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
              ),
              const SizedBox(height: 8),
              DropdownButtonFormField<ItemCondition>(
                initialValue: _selectedCondition,
                decoration: const InputDecoration(border: OutlineInputBorder()),
                items: ItemCondition.values.map((condition) {
                  return DropdownMenuItem(
                    value: condition,
                    child: Text(condition.displayName),
                  );
                }).toList(),
                onChanged: (value) {
                  if (value != null) {
                    setState(() {
                      _selectedCondition = value;
                    });
                  }
                },
              ),
              const SizedBox(height: 16),

              // Images
              const Text(
                'Photos',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
              ),
              const SizedBox(height: 8),
              if (_selectedImages.isEmpty)
                Container(
                  height: 120,
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.grey),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: InkWell(
                    onTap: _pickImages,
                    child: const Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(
                            Icons.add_photo_alternate,
                            size: 48,
                            color: Colors.grey,
                          ),
                          SizedBox(height: 8),
                          Text(
                            'Add Photos (Max 5)',
                            style: TextStyle(color: Colors.grey),
                          ),
                        ],
                      ),
                    ),
                  ),
                )
              else
                Column(
                  children: [
                    SizedBox(
                      height: 120,
                      child: ListView.builder(
                        scrollDirection: Axis.horizontal,
                        itemCount:
                            _selectedImages.length +
                            (_selectedImages.length < 5 ? 1 : 0),
                        itemBuilder: (context, index) {
                          if (index == _selectedImages.length) {
                            return Container(
                              width: 120,
                              margin: const EdgeInsets.only(right: 8),
                              decoration: BoxDecoration(
                                border: Border.all(color: Colors.grey),
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: InkWell(
                                onTap: _pickImages,
                                child: const Icon(
                                  Icons.add,
                                  size: 32,
                                  color: Colors.grey,
                                ),
                              ),
                            );
                          }

                          return Container(
                            width: 120,
                            margin: const EdgeInsets.only(right: 8),
                            child: Stack(
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.circular(8),
                                  child: FutureBuilder<Uint8List>(
                                    future: _selectedImages[index]
                                        .readAsBytes(),
                                    builder: (context, snapshot) {
                                      if (snapshot.hasData) {
                                        return Image.memory(
                                          snapshot.data!,
                                          width: 120,
                                          height: 120,
                                          fit: BoxFit.cover,
                                        );
                                      }
                                      return Container(
                                        width: 120,
                                        height: 120,
                                        color: Colors.grey[300],
                                        child: const Center(
                                          child: CircularProgressIndicator(),
                                        ),
                                      );
                                    },
                                  ),
                                ),
                                Positioned(
                                  top: 4,
                                  right: 4,
                                  child: InkWell(
                                    onTap: () => _removeImage(index),
                                    child: Container(
                                      padding: const EdgeInsets.all(4),
                                      decoration: const BoxDecoration(
                                        color: Colors.red,
                                        shape: BoxShape.circle,
                                      ),
                                      child: const Icon(
                                        Icons.close,
                                        color: Colors.white,
                                        size: 16,
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          );
                        },
                      ),
                    ),
                  ],
                ),
              const SizedBox(height: 16),

              // Meetup location
              TextFormField(
                controller: _meetupLocationController,
                decoration: const InputDecoration(
                  labelText: 'Meetup Location',
                  hintText: 'Where would you like to meet?',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.location_on),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter a meetup location';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),

              // Submit button
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _isSubmitting ? null : _submitTradeOffer,
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: _isSubmitting
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            valueColor: AlwaysStoppedAnimation<Color>(
                              Colors.white,
                            ),
                          ),
                        )
                      : const Text(
                          'Submit Trade Offer',
                          style: TextStyle(fontSize: 16),
                        ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
